FROM node:20-alpine

WORKDIR /app

COPY package*.json ./

RUN npm install 

COPY . .

# compila aplicacion, nos dice que al crear la imagen instal las cosas necesarias
RUN npm run build 

EXPOSE 8080


CMD [ "npm", "run", "serve" ]